---
- name: Install prerequisite packages
  loop: "{{ __packer_dependencies }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true

- name: Add the repository to APT sources
  ansible.builtin.deb822_repository:
    name: packer
    types: ["deb"]
    uris: "{{ __packer_base_url }}"
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: "{{ __packer_gpg_key_url }}"
    architectures: amd64
    enabled: true

- name: Install Packer
  ansible.builtin.apt:
    name: packer
    update_cache: true

- name: Verify the installation
  ansible.builtin.command:
    cmd: packer -version
  changed_when: false

- name: Add autocompletion for Packer
  ansible.builtin.command:
    cmd: packer -autocomplete-install
  register: packer_autocomplete
  failed_when: >
    packer_autocomplete.rc != 0 and
    'already installed' not in packer_autocomplete.stderr
  changed_when: packer_autocomplete.rc == 0
