---
- name: Install prerequisite packages
  loop: "{{ __packer_dependencies }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true

- name: Add the repository to APT sources
  ansible.builtin.deb822_repository:
    name: packer
    types: ["deb"]
    uris: "{{ __packer_base_url }}"
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: "{{ __packer_gpg_key_url }}"
    architectures: amd64
    enabled: true

- name: Install Packer
  ansible.builtin.apt:
    name: packer
    update_cache: true

- name: Add Packer autocompletion to .bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "complete -C /usr/bin/packer packer"
    state: present
